import { Grid, Text } from "@mantine/core";
import React from "react";
import { Language, LanguageProp } from "../MainPage";
import {
  NAVBAR_HEIGHT,
  OUTTER_GUTTER,
  OUTTER_GUTTER_MOBILE,
} from "../components/Navbar";
import useMediaQueryMd from "../features/useMediaQueryMd";

export interface TitleContentComponentProps {
  title: Record<Language, string>;
  content: Record<Language, string[]>;
}

export type TitleContentData = Array<TitleContentComponentProps>;

const titlesAndContent: TitleContentData = [
  {
    title: {
      en: "Privacy Policy",
      pt: "",
    },
    content: {
      en: [
        "SELO Estúdio Visual(SU), Limitada has great consideration and respect for the privacy of people with whom it interacts. SELO is committed to protecting your privacy and complying with the Law No. 22/11 of 17 June - Law for the Protection of Personal Data. This covers, in general, the collection and processing of personal data provided by customers, suppliers, users of social media pages and others, including those collected through forms, documents or other forms of communication with SELO Estúdio Visual(SU), Limitada.",
        "This Privacy Policy (Policy) describes how we collect, maintain, use and disclose your personal information, and how we maintain the quality and security of your personal information.",
        "For the convenience of understanding of this Policy, the definitions used are those contemplated in Law No. 22/11 of June 17 - Law for the Protection of Personal Data:",
      ],
      pt: [],
    },
  },
  {
    title: {
      en: "1. Responsible for handling personal data",
      pt: "",
    },
    content: {
      en: [
        '1.1 SELO is the entity responsible for the processing of personal data provided by the respective holder when filling out forms, as well as any other personal data which may be or have been provided in any other form, directly or indirectly, or which may have been generated by SELO, whether in the context of previous contacts or in the celebration, execution, renewal or termination of contracts, hereafter referred to as "Personal Data".',
        "1.2 The provision to SELO of personal data collected during pre-contractual procedures or during the hiring process, apart from those cases in which they correspond to information necessary for the fulfilment of SELO's legal obligations, will also be processed for the purposes of this policy.",
        "1.3 Personal data will be processed by the company, the entity responsible for data processing, for the purposes described in point 6 below, in strict compliance with the legislation in the matter of personal data protection.",
      ],
      pt: [],
    },
  },
  {
    title: {
      en: "2. Data Protection Officer",
      pt: "",
    },
    content: {
      en: [
        "2.1 The Data Protection Officer can be contacted in writing at the following addresses:",
        "technical@selovisualstudio.com",
      ],
      pt: [],
    },
  },
  {
    title: {
      en: "3. What is Personal Data?",
      pt: "",
    },
    content: {
      en: [
        '3.1 "Personal Data" means any information, whether true or not, and whether recorded in a material form or not, about an identified individual or identifiable individual.',
        "Broadly speaking, this includes information or an opinion that personally identifies you, either directly (for example, your name) or indirectly.",
      ],
      pt: [],
    },
  },
  {
    title: {
      en: "4. Processing of Personal Data",
      pt: "",
    },
    content: {
      en: [
        "4.1 The Personal Data provided at the time of contact or start of the relationship with SELO, are treated in strict accordance with the precepts established in the legislation applicable to the Protection of Personal Data, namely:",
        "- treated in a lawful, fair and transparent manner;",
        "- collected for specified, legitimate and explicit purposes and never further processed in a way incompatible with those purposes;",
        "- accurate and, as required, kept up to date, while providing for appropriate measures to ensure the deletion and rectification of incomplete or inaccurate data, taking into account the purposes for which they were collected or for which they are further processed;",
        "- kept in a form which permits the identification of data subjects for no longer than is necessary and legally required for the purposes for which the data were collected or for which they are to be further processed.",
      ],
      pt: [],
    },
  },
  {
    title: {
      en: "5. How do we collect your Personal Data?",
      pt: "",
    },
    content: {
      en: [
        "We collect your personal data directly when you:",
        "- interact with us by phone;",
        "- interact with us in person;",
        "- interact with us online;",
        "- participate in research, surveys or questionnaires;",
        "- participate in a SELO event;",
        "- subscribe to our newsletter and mailing list;",
        "- apply for a position with us as an employee, supplier or volunteer.",
      ],
      pt: [],
    },
  },
  {
    title: {
      en: "6. Purpose of Personal Data Processing",
      pt: "",
    },
    content: {
      en: [
        "6.1 The personal data provided by the holder or generated during the service provided will be processed and stored electronically for the exclusive use of SELO. We use and collect personal data strictly necessary and requested only for the purpose in question, for legitimate purposes, such as:",
        "- Provide requested information or services;",
        "- Offer a more personalized experience and service;",
        "- Improve the quality of services provided;",
        "- Meet internal administrative ends;",
        "- Perform marketing research and data analysis;",
        "- Comply with legal or regulatory requirements, necessary for the validity of certificates for some of the services offered, such as training initiatives;",
        "- Billing services/products.",
      ],
      pt: [],
    },
  },
  {
    title: {
      en: "7. Data Sharing",
      pt: "",
    },
    content: {
      en: [
        "7.1 SELO may share information with other entities which are directly or indirectly related to SELO, in compliance with the privacy policy implemented in accordance with applicable legal requirements, ensuring confidentiality and not exceeding the original purposes of processing.",
        "7.2 SELO may share information with other entities that provide services to it, in compliance with the privacy policy implemented in accordance with applicable legal requirements, ensuring confidentiality and not exceeding the original purposes of processing.",
      ],
      pt: [],
    },
  },
  {
    title: {
      en: "8. Transferring data outside Angola",
      pt: "",
    },
    content: {
      en: [
        "8.1 The transfer of personal information outside Angola will only happen with the data owner's consent if it is essential to comply with requests or orders sent to SELO, by legal requirement or for the better internal organisation of the company.",
        "8.2 SELO may also transfer its clients' personal data to comply with legal obligations or judicial requests, in particular, concerning legal responsibilities to collaborate with government institutions and authorities.",
      ],
      pt: [],
    },
  },
  {
    title: {
      en: "9. How do we protect your data?",
      pt: "",
    },
    content: {
      en: [
        "9.1 SELO ensures appropriate levels of security and protection of personal data and data owners. To this end, it implements multiple organizational, technical and physical security measures, to preserve information against change, dissemination, loss, unauthorized processing or access, as well as any other form of illegal processing."
      ],
      pt: [],
    },
  },
  {
    title: {
      en: "10. Online Activity",
      pt: "",
    },
    content: {
      en: [
        "10.1 Cookies SELO uses cookies on its website. These are small files made up of numbers and letters that are installed on your device, with your permission, when you access the site. Cookies allow the website to recognize your device, identifying it on subsequent visits and providing a better experience.",
        "10.1.2 Please note that we do not use cookies to identify you, only to optimize your experience on our site. If you prefer not to use them, you can change your browser settings to not have them automatically downloaded. However, it is important to remember that removing or blocking cookies may negatively affect your experience and functionality of our site.",
        "10.2 Direct Marketing: We may send you direct marketing communications and information about our services, opportunities or events that we consider may be of interest to you if you have requested or consented to receive such communications.",
      ],
      pt: [],
    },
  },
  {
    title: {
      en: "11. Data retention",
      pt: "",
    },
    content: {
      en: [
        "11.1 SELO complies with the legal regulations regarding the retention of personal data and may keep such data for:",
        "(a) Up to ten years after the end of the contract;",
        "b) While there are obligations resulting from the contractual relationship."
      ],
      pt: [],
    },
  },
  {
    title: {
      en: "12. How to access your Data",
      pt: ""
    },
    content: {
      en: [
        "12.1 SELO will strive to keep your personal information accurate, complete and up to date. If you wish to request to access and/or correct the personal data we hold about you, please request by contacting us via the contact details provided in number 2."
      ],
      pt: [

      ]
    }
  },
  {
    title: {
      en: "13. Privacy Policy Update",
      pt: ""
    },
    content: {
      en: [
        "13.1 SELO reserves the right to review, update, modify and replace this policy at any time, always by the principles stipulated in the legislation in force."
      ],
      pt: [

      ]
    }
  }
];

export const TitleContentComponent = ({
  title,
  content,
  language,
  index,
}: TitleContentComponentProps & { language: Language, index: number }) => {
  return (
    <>
      <Grid.Col xs={12} md={6} sx={{ marginTop: index === 0 ? undefined : `${OUTTER_GUTTER}px` }}>
        <Text fz="xl" fw={700}>
          {title[language]}
        </Text>
      </Grid.Col>
      <Grid.Col xs={12} md={6} sx={{ marginTop: index === 0 ? undefined : `${OUTTER_GUTTER}px` }}>
        {content[language].map((unitContent) => {
          return <Text>{unitContent}</Text>;
        })}
      </Grid.Col>
    </>
  );
};

const PrivacyPolicyPage: React.FC<LanguageProp> = ({ language }) => {
  const isSmallScreen = useMediaQueryMd();
  return (
    <Grid
      sx={{
        padding: `${NAVBAR_HEIGHT + OUTTER_GUTTER}px ${
          isSmallScreen ? OUTTER_GUTTER_MOBILE : OUTTER_GUTTER
        }px`,
        maxWidth: "100%",
        flexWrap: "wrap",
        // gap: `${OUTTER_GUTTER}px`,
      }}
    >
      {titlesAndContent.map(({ title, content }, index) => (
        <TitleContentComponent
          language={language}
          title={title}
          content={content}
          index={index}
        />
      ))}
    </Grid>
  );
};

export default PrivacyPolicyPage;
